// Demo data para o dashboard SDR — simula leads que chegariam via webhook Kommo.
// Esses dados aparecem se o localStorage estiver vazio. As SDRs podem usar para
// treinar e ver como a UI fica preenchida.

import type {
  SdrAgendaEvento,
  SdrConsulta,
  SdrLead,
  SdrMeta,
  SdrTarefa,
  SdrTratamento,
} from "@/types/sdr";

/**
 * Tipo do seed antes da normalização — `source` e `status` são preenchidos
 * automaticamente pelo store ao carregar (`normalizeLead` em sdr-store.ts).
 */
type SdrLeadSeed = Omit<SdrLead, "source" | "status">;

const HOJE = new Date();
function diasAtras(n: number): string {
  const d = new Date(HOJE);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}
function diasFrente(n: number): string {
  const d = new Date(HOJE);
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

export const SEED_LEADS: SdrLeadSeed[] = [
  {
    id: "lead_seed_001",
    externalId: 12345,
    tenantId: 789,
    nome: "João da Silva",
    telefone: "+55 11 98765-4321",
    tipo: "Cadastro",
    origem: "Campanha Meta (Instagram)",
    interacao: true,
    agendouConsulta: true,
    dataAgendamento: diasFrente(3),
    nomeResponsavel: "Maria Souza",
    login: "maria@clinica.com",
    observacao: "Lead chegou pelo Instagram, perguntou sobre hérnia inguinal",
    situacao: "Aguardando contato",
    clinica: "Doutor Hérnia · São Paulo",
    dataOrigem: diasAtras(0),
    dataModificacao: diasAtras(0),
    sourceFields: [
      "nome",
      "telefone",
      "origem",
      "tipo",
      "interacao",
      "nomeResponsavel",
      "login",
      "observacao",
      "situacao",
      "clinica",
      "dataOrigem",
      "dataModificacao",
    ],
    sourceProvenance: {
      receivedAt: diasAtras(0),
      webhookEvent: "CUSTOMER_CREATED",
      tenantId: 789,
    },
    createdAt: diasAtras(0),
  },
  {
    id: "lead_seed_002",
    externalId: 12346,
    tenantId: 789,
    nome: "Ana Carolina Pereira",
    telefone: "+55 11 99876-5432",
    tipo: "Resgate",
    origem: "Resgate: Ligação 3C",
    tipoResgate: "Ligação 3C",
    interacao: false,
    agendouConsulta: false,
    motivoNaoAgendamento: "Sem condições financeiras",
    nomeResponsavel: "Patrícia Lima",
    login: "patricia@clinica.com",
    situacao: "Resgate em curso",
    clinica: "Doutor Hérnia · São Paulo",
    dataOrigem: diasAtras(2),
    dataModificacao: diasAtras(1),
    sourceFields: [
      "nome",
      "telefone",
      "origem",
      "tipo",
      "tipoResgate",
      "interacao",
      "nomeResponsavel",
      "login",
      "situacao",
      "clinica",
      "dataOrigem",
      "dataModificacao",
    ],
    sourceProvenance: {
      receivedAt: diasAtras(2),
      webhookEvent: "CUSTOMER_CREATED",
      tenantId: 789,
    },
    createdAt: diasAtras(2),
  },
  {
    id: "lead_seed_003",
    externalId: 12347,
    tenantId: 789,
    nome: "Roberto Mendes",
    telefone: "+55 21 98765-1111",
    tipo: "Cadastro",
    origem: "Campanha Google",
    interacao: true,
    agendouConsulta: true,
    dataAgendamento: diasFrente(1),
    nomeResponsavel: "Maria Souza",
    login: "maria@clinica.com",
    observacao: "Cliente aguardando exame de imagem antes de fechar",
    situacao: "Agendado",
    clinica: "Doutor Hérnia · Rio de Janeiro",
    dataOrigem: diasAtras(5),
    dataModificacao: diasAtras(1),
    sourceFields: [
      "nome",
      "telefone",
      "origem",
      "tipo",
      "interacao",
      "nomeResponsavel",
      "login",
      "observacao",
      "situacao",
      "clinica",
      "dataOrigem",
      "dataModificacao",
    ],
    sourceProvenance: {
      receivedAt: diasAtras(5),
      webhookEvent: "CUSTOMER_UPDATED",
      tenantId: 789,
    },
    createdAt: diasAtras(5),
  },
  {
    id: "lead_seed_004",
    externalId: 12348,
    tenantId: 789,
    nome: "Lúcia Fernandes",
    telefone: "+55 31 97654-3210",
    tipo: "Cadastro",
    origem: "Indicação",
    interacao: true,
    agendouConsulta: false,
    motivoNaoAgendamento: "Vai pensar e retorna",
    nomeResponsavel: "Júlia Costa",
    login: "julia@clinica.com",
    situacao: "Aguardando retorno",
    clinica: "Doutor Hérnia · Belo Horizonte",
    dataOrigem: diasAtras(7),
    dataModificacao: diasAtras(3),
    sourceFields: [
      "nome",
      "telefone",
      "origem",
      "tipo",
      "interacao",
      "nomeResponsavel",
      "login",
      "situacao",
      "clinica",
      "dataOrigem",
      "dataModificacao",
    ],
    sourceProvenance: {
      receivedAt: diasAtras(7),
      webhookEvent: "CUSTOMER_CREATED",
      tenantId: 789,
    },
    createdAt: diasAtras(7),
  },
  {
    id: "lead_seed_005",
    externalId: 12349,
    tenantId: 789,
    nome: "Carlos Eduardo Silva",
    telefone: "+55 11 95555-7777",
    tipo: "Cadastro",
    origem: "Fachada",
    interacao: false,
    agendouConsulta: true,
    dataAgendamento: diasAtras(1),
    nomeResponsavel: "Patrícia Lima",
    login: "patricia@clinica.com",
    observacao: "Compareceu — fechou tratamento",
    situacao: "Compareceu",
    clinica: "Doutor Hérnia · São Paulo",
    dataOrigem: diasAtras(10),
    dataModificacao: diasAtras(1),
    sourceFields: [
      "nome",
      "telefone",
      "origem",
      "tipo",
      "nomeResponsavel",
      "login",
      "situacao",
      "clinica",
      "dataOrigem",
      "dataModificacao",
    ],
    sourceProvenance: {
      receivedAt: diasAtras(10),
      webhookEvent: "CUSTOMER_CREATED",
      tenantId: 789,
    },
    createdAt: diasAtras(10),
  },
];

export const SEED_CONSULTAS: SdrConsulta[] = [
  {
    id: "cons_seed_001",
    leadId: "lead_seed_005",
    dataConsulta: diasAtras(1),
    valorConsulta: 450,
    pago: true,
    recebimento1: { valor: 450, formaPagamento: "Pix", data: diasAtras(1) },
    status: "compareceu",
    tipoTratamentoIndicado: "Hérnia inguinal — cirurgia robótica",
    valorTratamento: 18000,
    fechouTratamento: true,
    observacao: "Paciente decidiu na consulta — pagou consulta no Pix",
    createdAt: diasAtras(1),
  },
  {
    id: "cons_seed_002",
    leadId: "lead_seed_003",
    dataConsulta: diasAtras(0),
    valorConsulta: 450,
    pago: false,
    status: "compareceu",
    tipoTratamentoIndicado: "Hérnia umbilical — avaliação",
    valorTratamento: 12000,
    fechouTratamento: false,
    motivoNaoFechamento: "Solicitado exame de imagem",
    observacao: "Vai trazer exame na próxima",
    createdAt: diasAtras(0),
  },
];

export const SEED_TRATAMENTOS: SdrTratamento[] = [
  {
    id: "trat_seed_001",
    consultaId: "cons_seed_001",
    leadId: "lead_seed_005",
    valor: 18000,
    recebimentos: [
      { valor: 6000, formaPagamento: "Pix", data: diasAtras(1) },
      { valor: 6000, formaPagamento: "Crédito 6x", data: diasAtras(1) },
    ],
    status: "em_andamento",
    tipoTratamento: "longo_3m",
    descricao: "Cirurgia robótica + 2 retornos pós-op",
    situacao: "Tratamento iniciado",
    createdAt: diasAtras(1),
  },
];

export const SEED_TAREFAS: SdrTarefa[] = [
  {
    id: "task_seed_001",
    dataVencimento: diasFrente(0),
    nome: "Confirmar agendamento João Silva",
    descricao: "Ligar para confirmar consulta de quinta",
    prioridade: "alta",
    status: "pendente",
    responsavel: "maria@clinica.com",
    createdAt: diasAtras(0),
  },
  {
    id: "task_seed_002",
    dataVencimento: diasFrente(1),
    nome: "Retornar Lúcia Fernandes",
    descricao: "Cliente pediu para pensar — ligar amanhã",
    prioridade: "media",
    status: "pendente",
    responsavel: "julia@clinica.com",
    createdAt: diasAtras(3),
  },
  {
    id: "task_seed_003",
    dataVencimento: diasAtras(1),
    nome: "Enviar orçamento Roberto Mendes",
    descricao: "Aguardando retorno do exame de imagem",
    prioridade: "alta",
    status: "em_andamento",
    responsavel: "maria@clinica.com",
    createdAt: diasAtras(2),
  },
];

export const SEED_AGENDA: SdrAgendaEvento[] = [
  {
    id: "agenda_seed_001",
    data: diasFrente(0),
    horaInicio: "09:00",
    horaFim: "10:00",
    descricao: "Consulta inicial — hérnia inguinal",
    nome: "João da Silva",
    status: "confirmado",
    responsavel: "maria@clinica.com",
    createdAt: diasAtras(0),
  },
  {
    id: "agenda_seed_002",
    data: diasFrente(1),
    horaInicio: "14:30",
    horaFim: "15:30",
    descricao: "Retorno — exame de imagem",
    nome: "Roberto Mendes",
    status: "agendado",
    responsavel: "maria@clinica.com",
    createdAt: diasAtras(1),
  },
  {
    id: "agenda_seed_003",
    data: diasFrente(2),
    horaInicio: "11:00",
    horaFim: "12:00",
    descricao: "Avaliação cirúrgica",
    nome: "Pedro Almeida",
    status: "agendado",
    responsavel: "patricia@clinica.com",
    createdAt: diasAtras(0),
  },
];

export const SEED_METAS: SdrMeta[] = [
  {
    id: "meta_seed_001",
    unidade: "Doutor Hérnia · São Paulo",
    mes: new Date().toISOString().slice(0, 7),
    login: "maria@clinica.com",
    secretaria: "Maria Souza",
    metaValor: 80000,
    realCadastro: 32,
    realResgate: 8,
    qtdTotal: 40,
    createdAt: diasAtras(0),
  },
  {
    id: "meta_seed_002",
    unidade: "Doutor Hérnia · São Paulo",
    mes: new Date().toISOString().slice(0, 7),
    login: "patricia@clinica.com",
    secretaria: "Patrícia Lima",
    metaValor: 80000,
    realCadastro: 24,
    realResgate: 12,
    qtdTotal: 36,
    createdAt: diasAtras(0),
  },
  {
    id: "meta_seed_003",
    unidade: "Doutor Hérnia · Rio de Janeiro",
    mes: new Date().toISOString().slice(0, 7),
    login: "julia@clinica.com",
    secretaria: "Júlia Costa",
    metaValor: 60000,
    realCadastro: 18,
    realResgate: 6,
    qtdTotal: 24,
    createdAt: diasAtras(0),
  },
];
